# Generated by Django 4.2 on 2023-05-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklineapp', '0003_rename_clave_usuario_password_usuario_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
