# Generated by Django 4.2 on 2023-05-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklineapp', '0005_userprofile_delete_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image',
        ),
    ]
